version: '3'
services:
  mongo:
    image: mongo:3.4.2
    expose:
      - "27017"
      - "37017"
    restart: always
    command: --smallfiles
  server:
    build: server
    volumes:
      - ./server/:/usr/src/app/:rw
      - /usr/src/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - mongo
  client:
    build: client
    volumes:
      - ./client/:/usr/src/app/:rw
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - server      